api_platform:
    title: Proconnect API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin', 'X-API-KEY']

        attributes:
            stateless: true

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
            X-API-KEY: # Ajout de l'en-tête X-API-KEY
                name: X-API-KEY
                type: header
