flasher:
  plugins:
    notyf:
      scripts:
        - '/vendor/flasher/flasher-notyf.min.js'
        - '/vendor/flasher/sweetalert2.min.js'
        - '/vendor/flasher/flasher-sweetalert.min.js'
      styles:
        - '/vendor/flasher/flasher-notyf.min.css'
        - '/vendor/flasher/sweetalert2.min.css'
      options:
        # Optional: Add global options here
#        position: center
        dismissible: true